name: "🏗️ Build Latest Packages"

env:
  TAG: workflow-${{ github.run_number }}
  SHA: ${{ github.sha }}

on:
  push:
    branches: [main]
    paths: [srcpkgs/**]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build📦 ${{ matrix.config.arch }}
    runs-on: ubuntu-latest
    permissions:
      contents: write   

    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: x86_64,       host: x86_64,      libc: glibc, platform: linux/amd64, test: 1 }
          - { arch: i686,         host: i686,        libc: glibc, platform: linux/amd64, test: 1 }
          - { arch: x86_64-musl,  host: x86_64-musl, libc: musl,  platform: linux/amd64, test: 1 }
          - { arch: aarch64,      host: aarch64,     libc: glibc, platform: linux/amd64, test: 0 }
          - { arch: aarch64-musl, host: aarch64-musl, libc: musl,  platform: linux/amd64, test: 0 }

    container:
      image: ghcr.io/void-linux/void-glibc-full:20250616R1
      options: --platform linux/amd64 --privileged
      volumes:
        - /dev:/dev
      env:
        TAG: '${{ env.TAG }}'
        SHA: '${{ env.SHA }}'
        ARCH: '${{ matrix.config.arch }}'
        XBPS_TARGET_ARCH: '${{ matrix.config.arch }}'
        REPO_OWNER: "${{ github.repository_owner }}"
        REPO_NAME: "${{ github.event.repository.name }}"

    if: ${{ github.ref == 'refs/heads/main' }}

    steps:    
      - name: 🐳 Prep container
        run: |
          mkdir -p /etc/xbps.d && cp /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/
          env -u XBPS_TARGET_ARCH xbps-install -Syu xbps
          env -u XBPS_TARGET_ARCH xbps-install -yu
          env -u XBPS_TARGET_ARCH xbps-install -y sudo bash curl git github-cli xtools coreutils qemu-user-static
          useradd -G xbuilder -M builder -s $(which bash)

      - name: 🔎 Checkout void-packages
        uses: actions/checkout@v6
        with:
          repository: void-linux/void-packages
          ref: master
          path: void-packages
           
      - name: 🧩 Merge this repository into void-linux/void-packages
        working-directory: void-packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "*"
          git remote add -f sofijacom https://github.com/sofijacom/xlibre-test.git
          git merge --no-commit --strategy-option=theirs --allow-unrelated-histories -Xignore-space-change sofijacom/main
          mkdir -p hostdir/binpkgs
          gh release download --pattern "*${ARCH}*" --dir hostdir/binpkgs --repo sofijacom/xlibre-test || true
          
      - name: 📋 Identify changes to build
        working-directory: void-packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          latest_name=$(gh release view --json tagName --jq '.tagName' --repo sofijacom/xlibre-test || echo "Initial Commit")
          latest_sha=$(git rev-list --max-count=1 ${latest_name} 2>/dev/null || git rev-list --max-parents=0 sofijacom/main)
          echo "Latest Tag Name: ${latest_name}"
          echo "Latest Tag SHA: ${latest_sha}"

          chown -R builder:builder .
          git diff-tree -r --no-renames --name-only --diff-filter=AM ${latest_sha} ${SHA} -- 'srcpkgs/**' \
          | cut -d/ -f 2 | uniq | xargs sudo -Eu builder ./xbps-src sort-dependencies | tee /tmp/templates

      - name: 📋 Setup void-packages
        working-directory: void-packages
        run: |
          chown -R builder:builder .
          mkdir -p etc
          echo XBPS_BUILD_ENVIRONMENT=void-packages-ci >> etc/conf
          echo XBPS_ALLOW_RESTRICTED=yes >> etc/conf
          echo XBPS_CHROOT_CMD=uchroot >> etc/conf
          echo 'XBPS_REPOSITORY=$PWD/hostdir/binpkgs' >> etc/conf
          echo 'XBPS_DISTDIR=$PWD/hostdir/distfiles' >> etc/conf
          echo 'XBPS_MASTERDIR_PKGS="$PWD/hostdir/binpkgs"' >> etc/conf

      - name: ✅ Prepare masterdir
        working-directory: void-packages
        run: |
          chown -R builder:builder .
          sudo -Eu builder \
            XBPS_NO_UNSHARE=1 \
            ./xbps-src -m masterdir-${{ matrix.config.arch }} -A ${{ matrix.config.arch }} binary-bootstrap

          if [ "${{ matrix.config.arch }}" = "aarch64" ] || [ "${{ matrix.config.arch }}" = "aarch64-musl" ]; then
            echo "🔧 Injecting qemu-aarch64-static into masterdir"
            mkdir -p masterdir-${{ matrix.config.arch }}/usr/bin
            cp /usr/bin/qemu-aarch64-static masterdir-${{ matrix.config.arch }}/usr/bin/
          fi

      - name: 📦 build pkgs
        working-directory: void-packages
        run: |
          chown -R builder:builder .
          pkgs=$(cat /tmp/templates)

          for pkg in $pkgs; do
            echo "🏗️ Building $pkg for $ARCH..."
            if [ "${{ matrix.config.arch }}" = "aarch64" ] || [ "${{ matrix.config.arch }}" = "aarch64-musl" ]; then
              sudo -Eu builder \
                XBPS_ALLOW_CHROOT_BREAKOUT=1 \
                ./xbps-src \
                  -m masterdir-${{ matrix.config.arch }} \
                  -A ${{ matrix.config.arch }} \
                  pkg -j$(nproc) "$pkg" || printf "Failed building $pkg!\n"
            else
              sudo -Eu builder \
                XBPS_NO_UNSHARE=1 \
                ./xbps-src \
                  -m masterdir-${{ matrix.config.arch }} \
                  -A ${{ matrix.config.arch }} \
                  pkg -j$(nproc) "$pkg" || printf "Failed building $pkg!\n"
            fi
          done

      - name: 🧾 Clean & sign
        working-directory: void-packages/hostdir/binpkgs
        env:
          PRIVKEY: ${{ secrets.PRIV_KEY }}
          XBPS_PASSPHRASE: ${{ secrets.SIGN_PASS }}
        run: |
          sudo -Eu builder xbps-rindex --remove-obsoletes ${PWD}
          printf "%s\n" "${PRIVKEY}" > key.pem
          sudo -Eu builder xbps-rindex --privkey key.pem --sign --signedby "${REPO_NAME}-github-actions" --verbose ${PWD}
          sudo -Eu builder xbps-rindex --privkey key.pem --sign-pkg --verbose ${PWD}/*.xbps
          sudo -Eu builder rm -f key.pem
          sudo -Eu builder xbps-rindex --clean ${PWD}

      - name: 🔢 checksum
        working-directory: void-packages/hostdir/binpkgs
        run: |
          rm -rf *.sha256sum *.sha512sum
          count=$(ls -1 *.xbps 2>/dev/null | wc -l)
          if [ "$count" != 0 ]; then
            for file in *.xbps; do
              sha256sum "${file}" | cut -d ' ' -f 1 > "${file}.sha256sum"
              sha512sum "${file}" | cut -d ' ' -f 1 > "${file}.sha512sum"
            done
          else
            echo "❌ No packages found to checksum."
          fi

      - name: 📤 Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.config.arch }}-repodata
          path: void-packages/hostdir/binpkgs

      - name: 🏷️ short sha
        run: |
          printf "SHORT_SHA=$(git rev-parse --short ${SHA})" >> $GITHUB_ENV

      - name: 🚀 release
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.SHORT_SHA }}
          tag_name: ${{ env.TAG }}
          files: |
            void-packages/hostdir/binpkgs/*.xbps
            void-packages/hostdir/binpkgs/*.sig2
            void-packages/hostdir/binpkgs/*repodata
