name: "🏗️ Build Latest Packages"
 
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-glibc-full:20250227R1
      options: --platform linux/amd64 --privileged

    env:
      TARGET_ARCH: x86_64

    steps:
      - name: 🔧 Подготовка
        run: |
          mkdir -p /etc/xbps.d && cp /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/
          sed -i 's|repo-default|repo-ci|g' /etc/xbps.d/*-repository-*.conf
          xbps-install -Syu xbps && xbps-install -yu
          xbps-install -y sudo git bash coreutils
          useradd -m -G xbuilder builder -s /bin/bash
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: 🌐 Клонируем void-packages
        run: |
          git clone --depth=1 https://github.com/void-linux/void-packages.git /home/builder/void-packages
          chown -R builder:xbuilder /home/builder/void-packages


      - name: 📦 binary-bootstrap
        run: |
          cd /home/builder/void-packages
          sudo -Eu builder \
          XBPS_NO_UNSHARE=1 \
          ./xbps-src -a x86_64 -A x86_64 binary-bootstrap
          # ВСЁ, ЧТО БЫЛО ПОСЛЕ — ЗАКОММЕНТИРОВАНО
          # - name: 🚀 Сборка...
          #   run: |
          #     ./xbps-src ...   ← ❌ вот он, враг

      - name: 🧪 Добавляем hello
        run: |
          cd /home/builder/void-packages
          mkdir -p srcpkgs/hello
          cat > srcpkgs/hello/template << 'EOF'
          pkgname=hello
          version=2.12
          revision=1
          build_style=gnu-configure
          short_desc="GNU Hello, the classic hello world program"
          maintainer="voidlinux@voidlinux.org"
          license="GPL-3.0-or-later"
          homepage="https://www.gnu.org/software/hello/"
          distfiles="https://ftp.gnu.org/gnu/hello/hello-${version}.tar.gz"
          checksum=64c9d4174ee312653359837626c7701a400959c9429195912e70f883168996f7
          EOF
          chown -R builder:xbuilder srcpkgs/hello

      - name: 🚀 Сборка ВНУТРИ chroot
        run: |
          cd /home/builder/void-packages
          MASTERDIR="masterdir-${TARGET_ARCH}"

          chroot "$MASTERDIR" /bin/sh -c "
            export XBPS_ALLOW_CHROOT_BREAKOUT=1
            cd /void-packages
            su - builder -c '
              ./xbps-src -a x86_64 pkg hello
            '
          "

      - name: 🗃️ Проверяем результат
        run: |
          find /home/builder/void-packages/hostdir/binpkgs -name "*.xbps" -ls

      - name: 📦 Артефакт
        uses: actions/upload-artifact@v4
        with:
          name: binpkgs
          path: /home/builder/void-packages/hostdir/binpkgs/**/*.xbps
